### ISSUE TITLE
The first trian phase

### ISSUE THREAD

**Issue by hongyugege** [placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography#1]
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoints/train1314/regression_original/epoch_85

**Comment by placeforyiming** [comment]
You can try train from scratch by setting epoch_start=1, lr=0.0001. Due to the space limit of Google drive, we only provide the final checkpoint.

**Comment by placeforyiming** [comment]
> RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoints/train1314/regression_original/epoch_85

I update the initial training settings, should work now

**Comment by hongyugege** [comment]
> > RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoints/train1314/regression_original/epoch_85
> 
> I update the initial training settings, should work now

okay  thanks very much
