### ISSUE TITLE
Method test in two different images

### ISSUE THREAD

**Issue by DoongLi** [placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography#10]
Hi, did you test two images with real multimodal and quantitatively evaluate the alignment? I think the data testing in the papers in the paper is simulated.

**Comment by placeforyiming** [comment]
> Hi, did you test two images with real multimodal and quantitatively evaluate the alignment? I think the data testing in the papers in the paper is simulated.

What do you mean by simulated? What are the "real multimodal" images do you think? 

 "align image pairs captured by different sensors or image pairs with large appearance changes" This is the first sentence in our paper to claim the problem we want to solve. 

"Google Earth provides high-resolution satellite images captured on different dates. So, we can choose images for the same place captured in different seasons." This is how we describe the Google Earth dataset, which is an example of image pairs with appearance differences. 

"Google Maps and Satellite are multimodal images provided by Google Static Map API. Two corresponding images belong to static Google Maps and satellite maps respectively" This is how we describe the Google Map dataset, which is an example of images from different sources.

**Comment by zzhunan** [comment]
hi~doctor，Could you please provide the loss landscape visualization code.
