### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by qian234** [placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography#2]
When I run the test_level_three.py, the extracted feature map is all white, and the code does not report an error, is it because the pre-training weight is not right? 

and Do you have a Pytorch version of your code?

Thanks very much!

**Comment by placeforyiming** [comment]
> When I run the test_level_three.py, the extracted feature map is all white, and the code does not report an error, is it because the pre-training weight is not right?
> 
> and Do you have a Pytorch version of your code?
> 
> Thanks very much!

Hi,

Can I ask which dataset did you try?
I just tried MSCOCO and GoogleMap, pre-trained checkpoints worked.

This project only has the tensorflow 2.0 version, we don't have plan to implement a pytorch version. Sorry about that.

Yiming

**Comment by placeforyiming** [comment]
Please feel free to open it again if this is still a question, thanks!

> When I run the test_level_three.py, the extracted feature map is all white, and the code does not report an error, is it because the pre-training weight is not right?
> 
> and Do you have a Pytorch version of your code?
> 
> Thanks very much!

Please feel free to open it again if this is still a question, thanks!
