### ISSUE TITLE
How can I get the warped image with this code like demo.gif?

### ISSUE THREAD

**Issue by qjr1997** [placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography#3]
I tried the “model_ours” to train “GoogleMap” . After that , I opened “Visualization.ipynb” and run it . I got the results like this.
![ec624ca062803c9e3253be1881d8e4d](https://user-images.githubusercontent.com/37289198/125717950-ca9e32f7-4c0e-474b-a270-0640558cf901.jpg)
I want to ask that how can I get the true warped image with this code.

**Comment by placeforyiming** [comment]
> I tried the “model_ours” to train “GoogleMap” . After that , I opened “Visualization.ipynb” and run it . I got the results like this.
> ![ec624ca062803c9e3253be1881d8e4d](https://user-images.githubusercontent.com/37289198/125717950-ca9e32f7-4c0e-474b-a270-0640558cf901.jpg)
> I want to ask that how can I get the true warped image with this code.

Hi,

The feature map has been extracted, then you need an initial guess of the homography and update the homography vector by using Lucas-Kanade on the feature map.

The initial guess can be:
1. A reasonable guess, for example, assume two images share the same center.
2. Classic methods, we tried the Fast-Match from the paper "Fast-match: Fast affine template matching" in the rebuttal.
3. In this paper, we trained two different networks to provide the initial guess.
4. If you want, you also can try if the traditional feature-based method, like harris corner, can provide a good initial

The better the initial guess, the larger chance Lucas-Kanade can converge.

**Comment by qjr1997** [comment]
Thank you for your reply ，
I still have some questions . “we trained two different networks to provide the initial guess” ，is that mean "DHN" and "MHN" mentioned in the paper ? Are they included in this code or I should find them from other places ？By the way I want to know what‘s the meaning of the parameter “regular” and “special” .

**Comment by placeforyiming** [comment]
> Thank you for your reply ，
> I still have some questions . “we trained two different networks to provide the initial guess” ，is that mean "DHN" and "MHN" mentioned in the paper ? Are they included in this code or I should find them from other places ？By the way I want to know what‘s the meaning of the parameter “regular” and “special” .

You can find them in this code under the folder model_ours.

One of our contribution is the feature constructor, the special means the feature map extract by our feature constructor, the regular means the feature map is just the output of a regular one channel conv
