### ISSUE TITLE
Homography for larger images

### ISSUE THREAD

**Issue by yaseryacoob** [placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography#5]
I am considering your solution for large images, let's say 1Kx1K (or even 10x10K). Do you have any suggestions as to the best way to do that?

**Comment by placeforyiming** [comment]
> I am considering your solution for large images, let's say 1Kx1K (or even 10x10K). Do you have any suggestions as to the best way to do that?

Hi,  I think the naive way is to either downsample the image or enlarge the network size. Probably combining those two can solve your problem. From my experience on this project, you can try to see if there are some common features that should be relied on while humans are trying to precisely align two images. Those common features are expected to be learned by the network. So those features should be preserved when downsampling images.

**Comment by placeforyiming** [comment]
please feel free to open it again
