### ISSUE TITLE
Repeatable training is not possible

### ISSUE THREAD

**Issue by vision-heng** [placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography#8]
When training the provided GoogleMap data using train_regression_first.py, I encountered a problem with NAN, which prevented the network from being trained effectively. What should I do to counter this problem?
![image](https://user-images.githubusercontent.com/55314052/199048098-e3eea67e-d7a3-4b1a-87e6-c6c7409b0d11.png)

**Comment by placeforyiming** [comment]
> When training the provided GoogleMap data using train_regression_first.py, I encountered a problem with NAN, which prevented the network from being trained effectively. What should I do to counter this problem? ![image](https://user-images.githubusercontent.com/55314052/199048098-e3eea67e-d7a3-4b1a-87e6-c6c7409b0d11.png)

Hi, 
I didn't touch the code for a while, and I don't have a GPU to try it now. But this part is a reproduced model from another paper. The idea of that paper is quite simple, just train a network to predict the homography parameters with simple regression loss. The only advanced contribution is using a multi-stage network to learn the residual in a hierarchical way. If you don't mind, you can try to build the network very soon I believe. 

The whole regression part is only used to give an initial, which is independent of the new technic in our paper. So you can still use our method to generate feature maps then followed by the LK method to get the final homography.

**Comment by vision-heng** [comment]
![image](https://user-images.githubusercontent.com/55314052/205204447-a97a32a3-a43d-45f8-8312-594def026068.png)

What is the difference between the options "special" or "regular" in "feature_map_type"?

**Comment by placeforyiming** [comment]
> ![image](https://user-images.githubusercontent.com/55314052/205204447-a97a32a3-a43d-45f8-8312-594def026068.png)
> 
> What is the difference between the options "special" or "regular" in "feature_map_type"?

line 663 in net.py
The only difference is the number of channels in the last layer. For the regular network, the output is the one-channel grey-scale-like feature map. But for the special network , the output is a tensor with 64 channels, then I add a feature extractor to extract the LK feature map.
