### ISSUE TITLE
some errors in codes

### ISSUE THREAD

**Issue by KN-Zhang** [placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography#9]
Hi! It is a nice work.
But I think, maybe, there are some code errors in calculating the second converge loss...

It seems that they have taken the negative of the Eq. (17) in the original paper.

I have revised it in my own codes and good results were got.

So I think you can have a check on it.

https://github.com/placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography/blob/5f678d1e61567990f321ea92f5619848f7426c98/model_ours/train_level_one.py#L385

https://github.com/placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography/blob/5f678d1e61567990f321ea92f5619848f7426c98/model_ours/train_level_one.py#L408

**Comment by 2970765122** [comment]
> Hi! It is a nice work. But I think, maybe, there are some code errors in calculating the second converge loss...
> 
> It seems that they have taken the negative of the Eq. (17) in the original paper.
> 
> I have revised it in my own codes and good results were got.
> 
> So I think you can have a check on it.
> 
> https://github.com/placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography/blob/5f678d1e61567990f321ea92f5619848f7426c98/model_ours/train_level_one.py#L385
> 
> https://github.com/placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography/blob/5f678d1e61567990f321ea92f5619848f7426c98/model_ours/train_level_one.py#L408

Hello, thank you for your question. To revise the equation, you can simply remove the negative sign at the beginning?

**Comment by placeforyiming** [comment]
> Hi! It is a nice work. But I think, maybe, there are some code errors in calculating the second converge loss...
> 
> It seems that they have taken the negative of the Eq. (17) in the original paper.
> 
> I have revised it in my own codes and good results were got.
> 
> So I think you can have a check on it.
> 
> https://github.com/placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography/blob/5f678d1e61567990f321ea92f5619848f7426c98/model_ours/train_level_one.py#L385
> 
> https://github.com/placeforyiming/CVPR21-Deep-Lucas-Kanade-Homography/blob/5f678d1e61567990f321ea92f5619848f7426c98/model_ours/train_level_one.py#L408

Could I know if you have figured out the problem?

I'm sorry, I have been working in the industry for a while, don't have too much time to check this research repo. If the problem has been solved, can I close this issue?
